apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  project: default
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
  destination:
    name: kind-test-1
    namespace: fluent-bit
  sources:
    # Source 1: JIT RBAC via Helm
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: jit-rbac-argo
      helm:
        releaseName: jit-fluent-bit
        valueFiles:
          - apps-rules/fluent-bit.yaml
    # Source 2: Helm chart
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: fluent-bit
      helm:
        releaseName: k8s-spb2-backend1-fluent-bit
        values: |
          kind: DaemonSet
          config:
            outputs: |
              [OUTPUT]
                  Name es
                  Match kube.*
                  Host elasticsearch-master.elasticsearch.svc.cluster.local
                  Port 9200
                  Logstash_Format On
                  Retry_Limit False
              
              [OUTPUT]
                  Name es
                  Match host.*
                  Host elasticsearch-master.elasticsearch.svc.cluster.local
                  Port 9200
                  Logstash_Format On
                  Logstash_Prefix node
                  Retry_Limit False
