apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  project: default
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
  destination:
    name: kind-test-1
    namespace: jaeger
  sources:
    # Source 1: JIT RBAC via Helm
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: jit-rbac-argo
      helm:
        releaseName: jit-jaeger
        valueFiles:
          - apps-rules/jaeger.yaml
    # Source 2: Helm chart
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: jaeger-operator
      helm:
        releaseName: k8s-spb2-backend1-jaeger
        values: |
          jaeger:
            create: true
            spec:
            strategy: production
            ingress:
              enabled: false
            agent:
              resources:
                limits:
                    cpu: 500m
                    memory: 256Mi
                requests:
                    cpu: 100m
                    memory: 64Mi
              sidecarSecurityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                runAsUser: 1001
                runAsGroup: 1001
                seccompProfile:
                  type: RuntimeDefault
                image: jaegertracing/jaeger-agent:1.49.0
            query:
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                    cpu: 500m
                    memory: 256Mi
                image: jaegertracing/jaeger-query:1.49.0
              tolerations:
                - key: "node-role.kubernetes.io/infr"
                  operator: "Exists"
                  effect: "NoSchedule"
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                          - key: "node-role.kubernetes.io/infr"
                            operator: "Exists"
            collector:
                replicas: 1
                image: jaegertracing/jaeger-collector:1.49.0
              options:
                collector:
                    num-workers: 10
                    queue-size: 1000
              resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits:
                    cpu: 500m
                    memory: 256Mi
              tolerations:
                - key: "node-role.kubernetes.io/infr"
                  operator: "Exists"
                  effect: "NoSchedule"
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                          - key: "node-role.kubernetes.io/infr"
                            operator: "Exists"
            storage:
              type: cassandra
              options:
                cassandra:
                  servers: cassandra-jaeger1.spb.dc,cassandra-jaeger2.spb.dc,cassandra-jaeger3.spb.dc
                  keyspace: jaeger_v1_ru_spb
              cassandraCreateSchema:
                enabled: false
              dependencies:
                enabled: false
              secretName: jaeger-secret
          webhooks:
            mutatingWebhook:
              create: false
            validatingWebhook:
              create: false
          rbac:
            create: true
            pspEnabled: false
            clusterRole: true
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          nodeSelector: {}
          tolerations:
            - key: "node-role.kubernetes.io/infr"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: "node-role.kubernetes.io/infr"
                        operator: "Exists"
