apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
  project: default
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
  destination:
    name: kind-test-1
    namespace: keda
  sources:
    # Source 1: JIT RBAC via Helm
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: jit-rbac-argo
      helm:
        releaseName: jit-keda
        valueFiles:
          - apps-rules/keda.yaml
    # Source 2: Helm chart
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: keda
      helm:
        releaseName: k8s-spb2-backend1-keda
        values: |
          image:
            keda:
              repository: ghcr.io/kedacore/keda
              tag: 2.16.1
            metricsApiServer:
              repository: ghcr.io/kedacore/keda-metrics-apiserver
              tag: 2.16.1
          webhooks:
            enabled: false
          crds:
            install: true
          certificates:
            autoGenerated: true
            certManager:
              enabled: false
          operator:
            livenessProbe:
              initialDelaySeconds: 60
              periodSeconds: 30
              timeoutSeconds: 10
              failureThreshold: 5
            readinessProbe:
              initialDelaySeconds: 40
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
          tolerations:
          - key: "node-role.kubernetes.io/infr"
            operator: "Exists"
            effect: "NoSchedule"
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                    - key: "node-role.kubernetes.io/infr"
                      operator: "Exists"
