apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-x509
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  project: default
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
  destination:
    name: kind-test-1
    namespace: x509-certificate-exporter
  sources:
    # Source 1: JIT RBAC via Helm
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: jit-rbac-argo
      helm:
        releaseName: jit-x509
        valueFiles:
          - apps-rules/x509.yaml
    # Source 2: Helm chart
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: x509-certificate-exporter
      helm:
        releaseName: k8s-spb2-backend1-x509
        values: |
          image:
            registry: docker.io
            repository: enix/x509-certificate-exporter
            tag: 3.6.0
          prometheusRules:
            create: false
          prometheusServiceMonitor:
            create: false
          secretsExporter:
            resources:
              limits:
                cpu: 500m
                memory: 150Mi
              requests:
                cpu: 500m
                memory: 150Mi
            tolerations:
              - key: "node-role.kubernetes.io/infr"
                operator: "Exists"
                effect: "NoSchedule"
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 1
                    preference:
                      matchExpressions:
                        - key: "node-role.kubernetes.io/infr"
                          operator: "Exists"
