apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-haproxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  project: default
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
  destination:
    name: kind-test-1
    namespace: haproxy
  sources:
    # Source 1: JIT RBAC (ClusterRole + ClusterRoleBinding)
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: jit-rbac-argo
      helm:
        releaseName: jit-haproxy
        valueFiles:
          - apps-rules/haproxy.yaml
    # Source 2: Helm chart
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: kubernetes-ingress
      helm:
        releaseName: haproxy-ingress
        values: |
          controller:
            kind: DaemonSet
            nodeSelector: null
            resources:
             limits:
               cpu: 2
               memory: 2Gi
             requests:
               cpu: 100m
               memory: 256Mi
            daemonset:
              useHostPort: true
              hostPorts:
                http: 80
                https: 443
                stat: 1024
                hlzcheck: 1042
            service:
              enabled: false
              ports:
                http: 80
                https: 443
                stat: 1024
                hlzcheck: 1042
              enablePorts:
                http: true
                https: true
                stat: true
                hlzcheck: true
              targetPorts:
                http: http
                https: https
                stat: stat
                hlzcheck: http
            serviceMonitor:
              enabled: false
            ingressClass: haproxy
            ingressClassResource:
              enabled: true
              name: haproxy
              default: false
