apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-policy-reporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
  project: default
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /metadata/labels/jit-rbac~1sync-status
        - /metadata/annotations
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: batch
      kind: Job
  destination:
    name: kind-test-1
    namespace: kyverno
  sources:
    # Source 1: JIT RBAC via Helm
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: jit-rbac-argo
      helm:
        releaseName: jit-policy-reporter
        valueFiles:
          - apps-rules/policy-reporter.yaml
    # Source 2: Helm chart
    - repoURL: 'https://github.com/nomad-mrkn/charts.git'
      targetRevision: HEAD
      path: policy-reporter
      helm:
        releaseName: policy-reporter
        values: |
          logging:
            encoding: json
          image:
            registry: ghcr.io
            repository: kyverno/policy-reporter
            tag: 2.20.1
          monitoring:
            enabled: false
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 50m
          replicaCount: 1
          leaderElection:
            enabled: false
          podDisruptionBudget:
            minAvailable: null
          ingress:
            enabled: false
          networkPolicy:
            enabled: false
          cronjob:
            violations:
              enabled: false
            summary:
              enabled: false
          tolerations: []
          nodeSelector: {}
          affinity: {}
