# Default values for jit-helm

appName: ""
namespace: ""
serviceAccountName: argocd-manager
serviceAccountNamespace: kube-system
roleName: ""

rules: []

markerRole:
  enabled: true
  rules: []

# image:
#   repository: registry.playteam.ru/bitnami/kubectl
#   tag: "1.31.0"
#   pullPolicy: IfNotPresent

image: bitnami/kubectl:latest

syncWave: "-1"
hookDeletePolicy: HookFailed
